### ISSUE TITLE
FALTA CONTENIDO!!

### ISSUE THREAD

**Issue by rubramriv73** [iesgrancapitan-entornos/2019-20-practica-5-github-issues-AntonioGGdev#1]
Antonio, por si no te has dado cuenta tu index.html esta completamente vacío añade información.

**Comment by AntonioGGdev** [comment]
Lo acabo de mirar y es cierto, lo arreglo en nada. Muchas gracias.

**Comment by rubramriv73** [comment]
A ti, estamos para ayudar :+1:
